### ISSUE TITLE
Beggar_background

### ISSUE THREAD

**Issue by Abysscrane** [NgGH707/World-Editor#1]
Just ran some fresh tests of WODeditor today and still getting same issues. Here are some logs to help figure out the problem.
__________
![Screenshot (109)](https://user-images.githubusercontent.com/101401938/164939277-2ba326aa-894b-4af5-9d01-774c9a930259.png)
![Screenshot (111)](https://user-images.githubusercontent.com/101401938/164939402-da47ed67-d6eb-425a-a64a-ce7d112efb86.png)
-The above is the error when running WOD with Legends + Magic Origins Hexe
__________
![Screenshot (113)](https://user-images.githubusercontent.com/101401938/164940500-12c1cb4b-7420-4f88-852e-d522ad3acf91.png)
-Above is error when running Northern Raiders (with Magic Origins installed)
__________
 
![Screenshot (115)](https://user-images.githubusercontent.com/101401938/164941328-6f056195-071f-4ed6-97af-dd026da38148.png)
-And finally running a Random Trio start (this time only Legends and WOD no Magic Origins)
_________

     Hope this helps figuring out the problem mate, cheers.

**Comment by NgGH707** [comment]
Fixed

**Comment by Abysscrane** [comment]
Yes background issues resolved, thanks.
